type: google.api.Service
config_version: 3

name: ss.endpoints.ignition-heart.cloud.goog

title: SS Service
apis:
  - name: service.HelloWorldService

usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true

