apiVersion: v1
kind: Service
metadata:
  name: grpc-calculation
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: grpc-calculation
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-calculation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-calculation
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-P", "9000",
          "-a", "grpc://127.0.0.1:50051",
          "-s", "sample.endpoints.ignition-heart.cloud.goog",
          "--rollout_strategy", "managed",
        ]
        ports:
          - containerPort: 9000
      - name: echo
        image: gcr.io/ignition-heart/go-grpc-calculation:1.0 # replace <YOUR_PROJECT_ID>
        ports:
          - containerPort: 50051
